export const styles = {
  authShell: "auth-shell",
  languageSelector: "",
  languageButton: "",
  languageDropdown: "",
  languageOption: "",
  authCard: "auth-card",
  authTitle: "",
  authSubtitle: "auth-subtitle",
  loginChoiceGrid: "login-choice-grid",
  choiceButton: "choice-btn",
  authForm: "auth-form",
  formLabel: "",
  formInput: "",
  formSelect: "",
  phoneRow: "phone-row",
  passwordWrap: "password-wrap",
  eyeButton: "eye-btn",
  authError: "auth-error",
  authSubmitButton: "auth-submit-btn",
  authActions: "auth-actions",
  authBackButton: "auth-back-btn",
  authLinkButton: "auth-link-btn",
};